version: '3.8'

services:
  rsyncd:
    container_name: rsyncd
    image: dannyshih/rsyncd:v3.2.3
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "873:873"
    volumes:
      - ./rsyncd.conf:/etc/rsyncd.conf
      - rsyncd_dev_lovegood:/shares/lovegood

volumes:
  rsyncd_dev_lovegood:
